# Generated by Django 5.1.4 on 2024-12-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0007_alter_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
